<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNwmtcqc\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNwmtcqc/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNwmtcqc.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNwmtcqc\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerNwmtcqc\appTestDebugProjectContainer(array(
    'container.build_hash' => 'Nwmtcqc',
    'container.build_id' => '214547b7',
    'container.build_time' => 1519814770,
));
