<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGufke5p\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGufke5p/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGufke5p.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGufke5p\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGufke5p\appProdProjectContainer(array(
    'container.build_hash' => 'Gufke5p',
    'container.build_id' => '120b4d0e',
    'container.build_time' => 1521039413,
));
